ffplot/ffplot/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

import playerdata.urls

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ffplot.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^playerdata/', include(playerdata.urls, namespace='playerdata')),
    url(r'^admin/', include(admin.site.urls)),
)

ffplot/playerdata/urls.py
from django.conf.urls import patterns, url

from playerdata import views

urlpatterns = patterns('', 
	url(r'^$', views.PlayersIndexView.as_view(), name='players_index'),
	url(r'^(?P<urlslug>\w+)/$', views.career_data_view, name='career_data'),
	url(r'^(?P<urlslug>\w+)/(?P<year>\w+)/$', views.season_data_view, 
		name='season_data'),
)

ffplot/core/models.py
from django.db import models


class TimeStampedModel(models.Model):
	"""
	an abstract base class that provides self-updating "created" and "modified" fields
	"""
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	
	class Meta:
		abstract = True

ffplot/playerdata/models.py
from django.db import models
from django.utils.text import slugify


# from .managers import PlayerManager, SeasonManager, GameManager
# from teamdata.models import TeamSeason, TeamGame


## ABSTRACT BASE CLASSES
		
class PlayerModel(models.Model):
	"""
	an abstract base class: career data fields applicable to all player positions
	"""
	headshot = models.ImageField('headshot', upload_to='media/player_headshots', 
								 null=True, blank=True)
	first_name = models.CharField('first name', max_length=50, null=True, blank=True)
	last_name = models.CharField('last_name', max_length=50, null=True, blank=True)
	position = models.CharField('position', max_length=2, null=True, blank=True, 
								choices=
							(('QB', 'Quarterback'), ('RB', 'Running Back'), 
							('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('K', 'Kicker'))
							)
	height = models.PositiveSmallIntegerField('height in inches', null=True, blank=True)
	weight = models.PositiveSmallIntegerField('weight in pounds', null=True, blank=True)
	dob = models.DateField('date of birth', null=True, blank=True)
	n_seasons = models.PositiveSmallIntegerField('number of seasons', null=True, blank=True)
	college = models.CharField('college', max_length=100, null=True, blank=True)
	
	urlslug = models.SlugField('urlslug', null=True, blank=True)
		
	def __str__(self):
		return '%s: %s, %s' % (self.position, self.last_name, self.first_name)
# 	objects = PlayerManager()
	
	class Meta:
		abstract = True
		

class SeasonModel(models.Model):
	"""
	an abstract base class: single season data fields applicable to all player positions
	"""
	number = models.PositiveSmallIntegerField('jersey number', null=True, blank=True)
	games_played = models.PositiveSmallIntegerField('regular season games played', 
													null=True, blank=True)
	year = models.PositiveSmallIntegerField('season year', null=True, blank=True)	
	
	def __str__(self):
		return '%s: %s: %s, %s' % (self.player.position, 
								   self.year, 
								   self.player.last_name, 
							 	   self.player.first_name)
# 	objects = SeasonManager()

	class Meta:
		abstract = True
	
	
class GameModel(models.Model):
	"""
	an abstract base class: single game data fields applicable to all player positions
	"""
	game_date = models.DateField('game date', null=True, blank=True)
	home_game = models.NullBooleanField('home game', null=True, blank=True)
	opponent = models.CharField('opponent', max_length=50, null=True, blank=True)	
# 	day_of_week = models.CharField('day of week', max_length=10, null=True, blank=True)

															 
	def __str__(self):
		return '%s: %s vs %s: %s, %s' % (self.season.player.position, 
										 self.game_date, 
										 self.opponent, 
										 self.season.player.last_name, 
									     self.season.player.first_name)
	
# 	objects = GameManager()
	
	class Meta:
		abstract = True
		
		
## RB CLASSES

class RbPlayer(PlayerModel):
	"""
	career data for running backs
	"""
	career_rushing_yards = models.IntegerField('career rushing yards', null=True, 
										    	blank=True)
	career_rushing_attempts = models.PositiveIntegerField('career rushing attempts',
														  null=True, blank=True)
	career_receiving_yards = models.IntegerField('career receiving yards', null=True, 
												 blank=True)
	career_receptions = models.IntegerField('career receptions', null=True, blank=True)
	

	
	
class RbSeason(SeasonModel):
	"""
	single season data for running backs
	"""
	player = models.ForeignKey(RbPlayer)
# 	team = models.ForeignKey(TeamSeason)
	season_rushing_yards = models.SmallIntegerField('season rushing yards', null=True, 
													blank=True)
	season_rushing_attempts = models.PositiveSmallIntegerField('season rushing attempts',
															   null=True, blank=True)
	
	
class RbGame(GameModel):
	"""
	single game data for running backs
	"""
	season = models.ForeignKey(RbSeason)
# 	game = models.ForeignKey(TeamGame)
# 	opponent_season = models.ForeignKey(TeamSeason)
	game_rushing_yards = models.SmallIntegerField('game rushing yards', null=True, 
											    	blank=True)
	game_rushing_attempts = models.PositiveSmallIntegerField('game rushing attempts', 
															 null=True, blank=True)

	
## QB CLASSES
	
# class QbPlayer(PlayerModel):
# 	"""
# 	career data for quarterbacks
# 	"""
# 	career_passing_yards = models.IntegerField(null=True, blank=True)
# 	career_passing_attempts = models.PositiveIntegerField(null=True, blank=True)
# 	
# 	
# class QbSeason(SeasonModel):
# 	"""
# 	single season data for quarterbacks
# 	"""
# 	player = models.ForeignKey(QbPlayer)
# 	season_passing_yards = models.SmallIntegerField(null=True, blank=True)
# 	season_passing_attempts = models.PositiveSmallIntegerField(null=True, blank=True)
# 	
# 	
# class QbGame(GameModel):
# 	"""
# 	single game data for quarterbacks
# 	"""
# 	season = models.ForeignKey(QbSeason)
# 	game_passing_yards = models.SmallIntegerField(null=True, blank=True)
# 	game_passing_attempts = models.PositiveSmallIntegerField(null=True, blank=True)
# 
# 
# class WrPlayer(PlayerModel):
# 	"""
# 	career data for wide receivers
# 	"""	
# 	

ffplot/core/views.py
from django.shortcuts import render

# Create your views here.

ffplot/playerdata/views.py
from django.shortcuts import render
from django.views import generic

from .models import RbPlayer, RbSeason, RbGame


class PlayersIndexView(generic.ListView):
	template_name = 'playerdata/base_playerdata.html'
	context_object_name = 'players_list'
	
	def get_queryset(self):
		return RbPlayer.objects.order_by('last_name')
	

def career_data_view(request, urlslug):
	position = urlslug.split('_')[-1].lower()
	season_field_names = ['year']
	if position == 'rb':
		player = RbPlayer.objects.get(urlslug=urlslug)
		seasons = player.rbseason_set.all()
		career_field_names = ['career_rushing_attempts', 'career_rushing_yards', 
							'career_receptions', 'career_receiving_yards', ]
		season_field_names += ['season_rushing_attempts', 'season_rushing_yards']
#	elif position = 'wr':
#		player = WrPlayer.objects.get(urlslug=urlslug)... etc
#	else:
#		return some error or 404
	career_field_data = [getattr(player, f) for f in career_field_names]
	season_field_data = [[getattr(s, f) for f in season_field_names] for s in seasons]
	template_name = 'playerdata/playerdata_career_data.html'
	context = {
				'player': player, 			
				'career_field_names': career_field_names, 
				'career_field_data': career_field_data, 
				'season_field_names': season_field_names, 
				'season_field_data': season_field_data,
				'season_field_numbers': list(range(len(season_field_names))),
		}
	return render(request, template_name, context)
	
	
def season_data_view(request, urlslug, year):
	position = urlslug.split('_')[-1].lower()
	season_field_names = ['year']
	game_field_names = ['game_date', 'opponent', 'home_game']
	if position == 'rb':
		player = RbPlayer.objects.get(urlslug=urlslug)
		season = player.rbseason_set.get(year=year)
		games = season.rbgame_set.all()
		season_field_names += ['season_rushing_attempts', 'season_rushing_yards']
		game_field_names += ['game_rushing_attempts', 'game_rushing_yards']
	season_field_data = [getattr(season, f) for f in season_field_names]
	game_field_data = [[getattr(g, f) for f in game_field_names] for g in games]
	template_name = 'playerdata/playerdata_season_data.html'
	context = {
				'season': season,
				'season_field_names': season_field_names,
				'season_field_data': season_field_data,
				'game_field_names': game_field_names,
				'game_field_data': game_field_data,
		}
	return render(request, template_name, context)
	
	
# class RbSeasonDataView(generic.DetailView):
# 	template_name = 'playerdata/playerdata_season_data.html'
# 	player = RbPlayer.objects.get(urlslug=urlslug)
# 	season = player.rbseason_set.get(year=year)
	
	

ffplot/templates/base.html
{# templates/base.html #}
<!DOCTYPE html>
<html>
	<head>
		{% block title %}<h1>ff plot</h1>{% endblock title %}
	</head>
	<body>
		<div id="sidebar">
        	<ul>
            	{# <li><a href="/">Home</a></li> #}
            	{# <li><a href="/blog/">Blog</a></li> #}
        	</ul>
    	</div>
    	<div id="content">
			{% block header %}
			<h2>football plots and data</h2>
			{% endblock header %}
			{% block content %}
			{% endblock content %}
		</div>
	</body>
</html>

ffplot/templates/playerdata/base_playerdata.html
{# templates/playerdata/base_playerdata.html #}
{% extends "base.html" %}

{% block header %}
	{{ block.super }}
	<h2>Players</h2>
{% endblock header %}
{% block content %}
	{# list of player name hyper links #}
	<ol>
    {% for player in players_list %}
        <li>
        	<a href="{% url 'playerdata:players_index' %}{{ player.urlslug }}">{{ player.last_name }}, {{ player.first_name }}</a>
        </li>
    {% endfor %}
    </ol>
{% endblock content %}
	

ffplot/templates/playerdata/playerdata_career_data.html
{# templates/playerdata/playerdata_career_data.html #}
{% extends "playerdata/base_playerdata.html" %}

{% load playerdata_custom_filters %}

{% block header %}
	<h2>{{ player.first_name }} {{ player.last_name }}</h2>
{% endblock header %}
{% block content %}
	<div>
		{# career table #}
		<TABLE BORDER="1" CELLSPACING="0" CELLPADDING="3">
		<TR>
		{% for field_name in career_field_names %}
			<TH>{{ field_name }}</TH>
		{% endfor %}
		</TR>
		<TR>
		{% for data in career_field_data %}
			<td>{{ data }}</td>
		{% endfor %}
		</TR>
		</TABLE>
	</div>
	<h2>Data by season</h2>
	<div>
		<TABLE BORDER="1" CELLSPACING="0" CELLPADDING="3">
		<TR>
		{% for field_name in season_field_names %}
			<TH>{{ field_name }}</TH>
		{% endfor %}
		</TR>
		{% for data_list in season_field_data %}
			<tr>
			{% for ii in season_field_numbers %}
				<td>
				{% if ii == 0 %}
				{# first column is season id, needs hyperlink to game log #}				
					<a href="{% url 'playerdata:players_index' %}{{ player.urlslug }}/{{ data_list|get_at_index:ii }}">{{ data_list|get_at_index:ii }}</a>
				{% else %}
					{{ data_list|get_at_index:ii }}
				{% endif %}
				</td>
			{% endfor %}
			</tr>
		{% endfor %}	
	</div>
	
			
{% endblock content %}

ffplot/templates/playerdata/playerdata_career_detail.html
{# templates/playerdata/playerdata_career_detail.html #}
{% extends "base_playerdata.html" %}

{% block header %}
	{# player name here #}
{% endblock header %}
{% block content %}
	{# data table here #}
{% endblock content %}

ffplot/templates/playerdata/playerdata_season_data.html
{# templates/playerdata/playerdata_season_data.html #}
{% extends "playerdata/base_playerdata.html" %}

{% block header %}
	<h2>{{ season.year }}: {{ season.player.first_name }} {{ season.player.last_name }}</h2>
{% endblock header %}
{% block content %}
	<div>
		{# season table #}
		<TABLE BORDER="1" CELLSPACING="0" CELLPADDING="3">
		<TR>
		{% for field_name in season_field_names %}
			<TH>{{ field_name }}</TH>
		{% endfor %}
		</TR>
		<TR>
		{% for data in season_field_data %}
			<td>{{ data }}</td>
		{% endfor %}
		</TR>
		</TABLE>
	</div>
	<h2>Data by game</h2>
	<div>
		<TABLE BORDER="1" CELLSPACING="0" CELLPADDING="3">
		<TR>
		{% for field_name in game_field_names %}
			<TH>{{ field_name }}</TH>
		{% endfor %}
		</TR>
		{% for data_list in game_field_data %}
			<tr>
			{% for data in data_list %}
				<td>
				{{ data }}
				</td>
			{% endfor %}
			</tr>
		{% endfor %}	
	</div>
{% endblock content %}